package problemsolver;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kylle
 */

public class CalcFrame extends javax.swing.JFrame {
    
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalcFrame.class.getName());
private double firstOperand = 0;
private String operator = "";
private boolean startNewNumber = true;
    /**
     * Creates new form CalcFrame
     */
    public CalcFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
      private void initComponents() {
 
        jButton15 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
 
        jButton15.setText("jButton15");
        
        
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
           jTextField1.setText("0");
        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
 
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4));
 
        jButton1.setText("C");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
 
        jButton2.setText("[]");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);
 
        jButton3.setText("%");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);
 
        jButton4.setText("/");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4);
 
        jButton5.setText("7");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel1.add(jButton5);
 
        jButton6.setText("8");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel1.add(jButton6);
 
        jButton7.setText("9");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jPanel1.add(jButton7);
 
        jButton8.setText("x");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jPanel1.add(jButton8);
 
        jButton9.setText("4");
        jButton9.addActionListener(this::jButton9ActionPerformed);
        jPanel1.add(jButton9);
 
        jButton10.setText("5");
        jButton10.addActionListener(this::jButton10ActionPerformed);
        jPanel1.add(jButton10);
 
        jButton11.setText("6");
        jButton11.addActionListener(this::jButton11ActionPerformed);
        jPanel1.add(jButton11);
 
        jButton12.setText("-");
        jButton12.addActionListener(this::jButton12ActionPerformed);
        jPanel1.add(jButton12);
 
        jButton13.setText("1");
        jButton13.addActionListener(this::jButton13ActionPerformed);
        jPanel1.add(jButton13);
 
        jButton14.setText("2");
        jButton14.addActionListener(this::jButton14ActionPerformed);
        jPanel1.add(jButton14);
 
        jButton21.setText("3");
        jButton21.addActionListener(this::jButton21ActionPerformed);
        jPanel1.add(jButton21);
 
        jButton16.setText("+");
        jButton16.addActionListener(this::jButton16ActionPerformed);
        jPanel1.add(jButton16);
 
        jButton17.setText("+-");
        jButton17.addActionListener(this::jButton17ActionPerformed);
        jPanel1.add(jButton17);
 
        jButton18.setText("0");
        jButton18.addActionListener(this::jButton18ActionPerformed);
        jPanel1.add(jButton18);
 
        jButton19.setText(".");
        jButton19.addActionListener(this::jButton19ActionPerformed);
        jPanel1.add(jButton19);
 
        jButton20.setText("=");
        jButton20.addActionListener(this::jButton20ActionPerformed);
        jPanel1.add(jButton20);
        
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
 
        pack();
    }// </editor-fold>
        
       private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Display field is not editable; nothing needed here.
    }
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { // C
        jTextField1.setText("0");
        firstOperand = 0;
        operator = "";
        startNewNumber = true;
    }
          private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { // [] backspace
        String current = jTextField1.getText();
        if (current.length() > 1) {
            jTextField1.setText(current.substring(0, current.length() - 1));
        } else {
            jTextField1.setText("0");
            startNewNumber = true;
        }
    }
          
           private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { // %
        double value = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(format(value / 100));
        startNewNumber = true;
    }
           
           
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton15 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        jButton15.setText("jButton15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Kylle's Calculator");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        jButton1.setText("C");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        jButton2.setText("[x]");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);

        jButton3.setText("%");
        jPanel1.add(jButton3);

        jButton4.setText("/");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4);

        jButton5.setText("7");
        jPanel1.add(jButton5);

        jButton6.setText("8");
        jPanel1.add(jButton6);

        jButton7.setText("9");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jPanel1.add(jButton7);

        jButton8.setText("x");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jPanel1.add(jButton8);

        jButton9.setText("4");
        jPanel1.add(jButton9);

        jButton10.setText("5");
        jPanel1.add(jButton10);

        jButton11.setText("6");
        jPanel1.add(jButton11);

        jButton12.setText("-");
        jPanel1.add(jButton12);

        jButton13.setText("1");
        jPanel1.add(jButton13);

        jButton14.setText("2");
        jPanel1.add(jButton14);

        jButton21.setText("3");
        jButton21.addActionListener(this::jButton21ActionPerformed);
        jPanel1.add(jButton21);

        jButton16.setText("+");
        jPanel1.add(jButton16);

        jButton17.setText("+-");
        jPanel1.add(jButton17);

        jButton18.setText("0");
        jPanel1.add(jButton18);

        jButton19.setText(".");
        jPanel1.add(jButton19);

        jButton20.setText("=");
        jPanel1.add(jButton20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalcFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
